---
- name: Update locales
  locale_gen: name=en_US.UTF-8 state=present

- name: Default locales
  copy:
    src: locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  tags: bootstrap

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: update_cache

- name: Install common tools
  apt: pkg={{ item }} state=present
  with_items:
    - htop
    - tree
    - tmux
    - python-software-properties
    - curl

- name: Install common requirements
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - git
    - redis-server
  tags: bootstrap

- name: Engine requirements
  apt: pkg={{ item }} state=present
  with_items:
    - libjpeg62
    - libjpeg62-dev
    - zlib1g-dev
    - imagemagick
    - graphicsmagick
    - libboost-python-dev